MAX_CPU_TIME_LIMIT=10
MAX_REAL_TIME_LIMIT=15
MAX_MEMORY_LIMIT=2048000
MAX_PROCESSES_AND_OR_THREADS=256
MAX_MAX_PROCESSES_AND_OR_THREADS=512
ENABLE_NETWORK=false
REDIS_HOST=redis
REDIS_PORT=6379
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0
